# Generated by Django 5.0.6 on 2024-06-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('owner', 'Владелец'), ('user', 'Пользователь')], default='user', max_length=10),
        ),
    ]
