# Generated by Django 5.2.9 on 2025-12-11 23:59

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import reservations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Наименование кухни",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание кухни"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Уникальный идентификатор",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Кухня",
                "verbose_name_plural": "Кухни",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Особенность"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Уникальный идентификатор",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Особенность",
                "verbose_name_plural": "Особенности",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название меню"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
            },
        ),
        migrations.CreateModel(
            name="PlaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Тип заведения"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, unique=True, verbose_name="Уникальный идентификатор"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Тип заведения",
                "verbose_name_plural": "Типы заведений",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название тега"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100,
                        unique=True,
                        verbose_name="Уникальный идентификатор",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название блюда"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="menu_images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Доступно"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="reservations.menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "street_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("улица", "ул."),
                            ("проспект", "пр-кт"),
                            ("переулок", "пер."),
                            ("набережная", "наб."),
                            ("бульвар", "б-р"),
                            ("шоссе", "ш."),
                            ("площадь", "пл."),
                            ("аллея", "ал."),
                            ("линия", "лн."),
                            ("проезд", "пр-д"),
                        ],
                        default="",
                        max_length=50,
                        null=True,
                        verbose_name="Тип улицы",
                    ),
                ),
                (
                    "street_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название улицы",
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Номер дома"
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True,
                        help_text="Укажите этаж, если заведение находится не на первом этаже",
                        max_length=5,
                        null=True,
                        verbose_name="Этаж",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона должен быть введен в формате: '+79999999999'. Допустимо до 12 цифр.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.URLValidator],
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.URLValidator],
                    ),
                ),
                (
                    "telegram",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.URLValidator],
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона должен быть введен в формате: '+79999999999'. Допустимо до 12 цифр.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "viber",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона должен быть введен в формате: '+79999999999'. Допустимо до 12 цифр.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "vkontakte",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.URLValidator],
                        verbose_name="ВКонтакте",
                    ),
                ),
                (
                    "odnoklassniki",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.URLValidator],
                        verbose_name="Одноклассники",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.EmailValidator],
                        verbose_name="Эл. почта",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Веб-сайт")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "average_check",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Средний чек"
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Вместимость"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Уникальный идентификатор",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активное"
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Популярное"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Рекомендуемое"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="locations.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "cuisines",
                    models.ManyToManyField(
                        blank=True,
                        related_name="places",
                        to="reservations.cuisine",
                        verbose_name="Кухни",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Представитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заведение",
                "verbose_name_plural": "Заведения",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="reservations.place",
            ),
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название зоны"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("real", "Реальная"), ("virtual", "Виртуальная")],
                        default="real",
                        max_length=10,
                        verbose_name="Вид зоны",
                    ),
                ),
                (
                    "hall_type",
                    models.CharField(
                        choices=[
                            ("outdoor", "На улице"),
                            ("panoramic_windows", "Панорамные окна"),
                            ("terrace", "Терраса"),
                            ("main_hall", "Основной зал"),
                            ("small_hall", "Малый зал"),
                            ("vip_hall", "ВИП зал"),
                            ("booth", "Кабинка"),
                        ],
                        max_length=20,
                        verbose_name="Тип зоны",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "number_of_seats",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество посадочных мест"
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Площадь (м²)",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="halls",
                        to="reservations.place",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зона",
                "verbose_name_plural": "Зоны",
                "unique_together": {("place", "name")},
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название события"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("date", models.DateField(verbose_name="Дата")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "image",
                    models.ImageField(upload_to="events/", verbose_name="Изображение"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активное мероприятие"
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="reservations.place",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название акции"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Процент скидки"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="discounts/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="reservations.place",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
            },
        ),
        migrations.CreateModel(
            name="BookingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accepts_bookings",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, если хотите разрешить бронирования для этого заведения",
                        verbose_name="Доступно для бронирования",
                    ),
                ),
                (
                    "booking_interval",
                    models.PositiveIntegerField(
                        choices=[
                            (5, "5 минут"),
                            (10, "10 минут"),
                            (15, "15 минут"),
                            (30, "30 минут"),
                            (60, "1 час"),
                        ],
                        default=30,
                        help_text="Выберите интервал для шагов времени в форме бронирования",
                        verbose_name="Шаг выбора минут",
                    ),
                ),
                (
                    "unavailable_interval",
                    models.PositiveIntegerField(
                        choices=[
                            (10, "10 минут"),
                            (20, "20 минут"),
                            (30, "30 минут"),
                            (40, "40 минут"),
                            (50, "50 минут"),
                            (60, "1 час"),
                        ],
                        default=30,
                        help_text="Укажите интервал в минутах, который недоступен для бронирования перед текущим временем",
                        verbose_name="Недоступный интервал для бронирования от текущего времени",
                    ),
                ),
                (
                    "default_guest_count",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Количество гостей по умолчанию"
                    ),
                ),
                (
                    "allow_table_selection",
                    models.BooleanField(
                        default=True,
                        help_text="Столики нужно добавить в разделе «Столики»",
                        verbose_name="Выбор столика на форме бронирования",
                    ),
                ),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True,
                        help_text="Оставьте пустым, чтобы не получать уведомления по электронной почте",
                        max_length=255,
                        null=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Введите корректный email адрес."
                            )
                        ],
                        verbose_name="Email для уведомлений о бронированиях",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "place",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_settings",
                        to="reservations.place",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки бронирования",
                "verbose_name_plural": "Настройки бронирования",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_time",
                    models.DateTimeField(verbose_name="Время бронирования"),
                ),
                ("guests_count", models.IntegerField(verbose_name="Количество гостей")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="reservations.place",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.CreateModel(
            name="PlaceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание особенности"
                    ),
                ),
                (
                    "display_on_card",
                    models.BooleanField(
                        default=False, verbose_name="Отображать на карточке"
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_features",
                        to="reservations.feature",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_features",
                        to="reservations.place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Особенность заведения",
                "verbose_name_plural": "Особенности заведения",
                "unique_together": {("place", "feature")},
            },
        ),
        migrations.AddField(
            model_name="place",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                related_name="places",
                through="reservations.PlaceFeature",
                to="reservations.feature",
                verbose_name="Особенности",
            ),
        ),
        migrations.CreateModel(
            name="PlaceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=reservations.models.upload_to_instance_directory,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на видео"
                    ),
                ),
                (
                    "embed_code",
                    models.TextField(
                        blank=True, null=True, verbose_name="Код для встраивания видео"
                    ),
                ),
                (
                    "is_cover",
                    models.BooleanField(default=False, verbose_name="Обложка"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="reservations.hall",
                        verbose_name="Зона",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="reservations.place",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медиа заведения",
                "verbose_name_plural": "Медиа заведений",
            },
        ),
        migrations.AddField(
            model_name="place",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="places",
                to="reservations.placetype",
                verbose_name="Тип",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(5)]
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает модерации"),
                            ("approved", "Одобрен"),
                            ("spam", "Спам"),
                            ("inappropriate", "Неуместный"),
                        ],
                        default="approved",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="reservations.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="review_images/", verbose_name="Изображение"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="reservations.review",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(5)],
                        verbose_name="Текст ответа",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата ответа"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления ответа"
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="reservations.place",
                    ),
                ),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="reservations.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на отзыв",
                "verbose_name_plural": "Ответы на отзывы",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Наименование столика"
                    ),
                ),
                (
                    "seats",
                    models.PositiveIntegerField(
                        default=4, verbose_name="Количество мест"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="table_photos/",
                        verbose_name="Фото столика",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Количество столиков данного вида"
                    ),
                ),
                (
                    "min_booking_seats",
                    models.PositiveIntegerField(
                        default=2,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Минимальное количество мест для бронирования",
                    ),
                ),
                (
                    "min_booking_period",
                    models.DurationField(
                        default=datetime.timedelta(seconds=1800),
                        verbose_name="Минимальный период бронирования",
                    ),
                ),
                (
                    "max_booking_period",
                    models.DurationField(
                        default=datetime.timedelta(seconds=7200),
                        verbose_name="Максимальный период бронирования",
                    ),
                ),
                (
                    "booking_payment",
                    models.CharField(
                        choices=[("advance", "Аванс"), ("no_advance", "Без аванса")],
                        default="no_advance",
                        max_length=10,
                        verbose_name="Оплата бронирования",
                    ),
                ),
                (
                    "booking_interval",
                    models.DurationField(
                        default=datetime.timedelta(seconds=1800),
                        verbose_name="Период между бронированиями",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="reservations.hall",
                        verbose_name="Зал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        editable=False, unique=True, verbose_name="Номер заказа"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата бронирования"
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время бронирования"
                    ),
                ),
                (
                    "guests",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество гостей",
                    ),
                ),
                ("wishes", models.TextField(blank=True, verbose_name="Пожелания")),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Имя и фамилия"),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона должен быть введен в формате: '+79999999999'",
                                regex="^\\+?1?\\d{9,12}$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтвержден рестораном"),
                            ("cancelled_by_restaurant", "Отменен рестораном"),
                            ("cancelled_by_customer", "Отменен клиентом"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="reservations.place",
                        verbose_name="Заведение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="reservations.table",
                        verbose_name="Столик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="PlaceUpdateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает рассмотрения"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "updated_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Название заведения",
                    ),
                ),
                (
                    "updated_street_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("улица", "ул."),
                            ("проспект", "пр-кт"),
                            ("переулок", "пер."),
                            ("набережная", "наб."),
                            ("бульвар", "б-р"),
                            ("шоссе", "ш."),
                            ("площадь", "пл."),
                            ("аллея", "ал."),
                            ("линия", "лн."),
                            ("проезд", "пр-д"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Тип улицы",
                    ),
                ),
                (
                    "updated_street_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название улицы",
                    ),
                ),
                (
                    "updated_house_number",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Номер дома"
                    ),
                ),
                (
                    "updated_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Телефон заведения",
                    ),
                ),
                (
                    "updated_facebook",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="Facebook"
                    ),
                ),
                (
                    "updated_instagram",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="Instagram"
                    ),
                ),
                (
                    "updated_telegram",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="Telegram"
                    ),
                ),
                (
                    "updated_whatsapp",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "updated_vkontakte",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="ВКонтакте"
                    ),
                ),
                (
                    "updated_website",
                    models.URLField(blank=True, verbose_name="Веб-сайт"),
                ),
                (
                    "updated_description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "updated_short_description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "updated_average_check",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Средний чек"
                    ),
                ),
                (
                    "updated_capacity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Вместимость"
                    ),
                ),
                (
                    "updated_cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="place_images/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_requests",
                        to="reservations.place",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_features",
                    models.ManyToManyField(
                        blank=True,
                        related_name="update_requests",
                        to="reservations.feature",
                        verbose_name="Особенности заведения",
                    ),
                ),
                (
                    "updated_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reservations.placetype",
                        verbose_name="Тип заведения",
                    ),
                ),
                (
                    "updated_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="update_requests",
                        to="reservations.tag",
                        verbose_name="Теги",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="places",
                to="reservations.tag",
                verbose_name="Теги",
            ),
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "Понедельник"),
                            ("TUE", "Вторник"),
                            ("WED", "Среда"),
                            ("THU", "Четверг"),
                            ("FRI", "Пятница"),
                            ("SAT", "Суббота"),
                            ("SUN", "Воскресенье"),
                        ],
                        max_length=3,
                        verbose_name="День недели",
                    ),
                ),
                (
                    "open_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время открытия"
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время закрытия"
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Выходной"),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedule",
                        to="reservations.place",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Время работы",
                "verbose_name_plural": "Время работы",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="reservations.place",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранные",
                "unique_together": {("user", "place")},
            },
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["place"], name="reservation_place_i_0740ce_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user"], name="reservation_user_id_5ae977_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "place")},
        ),
        migrations.AlterUniqueTogether(
            name="workschedule",
            unique_together={("place", "day")},
        ),
    ]
