# Generated by Django 5.0.6 on 2024-06-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование кухни'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='closing_time',
            field=models.TimeField(verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='opening_time',
            field=models.TimeField(verbose_name='Время открытия'),
        ),
    ]
