# Generated by Django 5.2.9 on 2025-12-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="house_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Номер дома"
            ),
        ),
    ]
