# Generated by Django 5.0.6 on 2024-06-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_cuisine_name_alter_establishment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активное заведение'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
