# Generated by Django 5.2.9 on 2025-12-14 19:57

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_alter_place_house_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=reservations.models.upload_to_instance_directory,
                validators=[reservations.models.validate_image_min_size],
                verbose_name="Изображение",
            ),
        ),
    ]
