# Generated by Django 5.0.6 on 2024-06-14 20:18

import django.core.validators
import django.db.models.deletion
import reservations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_establishment_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип заведения')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Уникальный идентификатор')),
            ],
            options={
                'verbose_name': 'Тип заведения',
                'verbose_name_plural': 'Типы заведений',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='cuisines',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='review',
            name='establishment',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='establishment',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='establishment',
        ),
        migrations.RemoveField(
            model_name='table',
            name='establishment',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='establishment',
        ),
        migrations.RemoveField(
            model_name='event',
            name='establishment',
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'Время работы', 'verbose_name_plural': 'Время работы'},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='num_people',
            new_name='guests',
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название заведения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес заведения')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в формате: '+999999999'. Допустимо до 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон заведения')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('average_check', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средний чек')),
                ('has_kids_room', models.BooleanField(default=False, verbose_name='Наличие детской комнаты')),
                ('capacity', models.IntegerField(default=0, verbose_name='Вместимость')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активное заведение')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Уникальный идентификатор')),
                ('cuisines', models.ManyToManyField(blank=True, to='reservations.cuisine', verbose_name='Кухни')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='reservations.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reservations.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='reservations.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.place', verbose_name='Заведение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reservations.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='reservations.place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.place'),
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=reservations.models.upload_to_instance_directory, verbose_name='Изображение')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Обложка')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reservations.place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for', to='reservations.placeimage'),
        ),
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.placetype', verbose_name='Тип заведения'),
        ),
        migrations.DeleteModel(
            name='EstablishmentImage',
        ),
        migrations.DeleteModel(
            name='Establishment',
        ),
    ]
