# Generated by Django 5.0.6 on 2024-06-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_placetype_remove_establishment_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='average_check',
            field=models.IntegerField(default=0, verbose_name='Средний чек'),
        ),
    ]
