# Generated by Django 5.0.6 on 2024-06-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_place_average_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Особенность')),
            ],
            options={
                'verbose_name': 'Особенность',
                'verbose_name_plural': 'Особенности',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='features',
            field=models.ManyToManyField(blank=True, to='reservations.feature', verbose_name='Особенности заведения'),
        ),
    ]
