# Generated by Django 5.0.6 on 2024-06-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_feature_place_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Город')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Уникальный идентификатор')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Особенность'),
        ),
    ]
