# Generated by Django 5.0.6 on 2024-06-18 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_city_alter_feature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='reservations.city', verbose_name='Город заведения'),
            preserve_default=False,
        ),
    ]
