# Generated by Django 5.0.6 on 2024-06-18 22:34

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_city_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=reservations.models.upload_to_city_image, verbose_name='Изображение'),
        ),
    ]
