# Generated by Django 5.0.6 on 2024-06-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_alter_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Уникальный идентификатор'),
        ),
    ]
