# Generated by Django 5.0.6 on 2024-06-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_reservation_email_reservation_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='order_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер заказа'),
        ),
    ]
