# Generated by Django 5.0.6 on 2024-06-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_alter_reservation_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='order_number',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Номер заказа'),
        ),
    ]
