# Generated by Django 5.0.6 on 2024-06-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_alter_reservation_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время бронирования'),
        ),
    ]
