# Generated by Django 5.0.6 on 2024-06-19 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_alter_reservation_date_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for', to='reservations.placeimage', verbose_name='Обложка'),
        ),
    ]
