# Generated by Django 5.0.6 on 2024-06-19 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_alter_place_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='establishment',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.place', verbose_name='Заведение'),
            preserve_default=False,
        ),
    ]
