# Generated by Django 5.0.6 on 2024-06-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_remove_workschedule_establishment_workschedule_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='order_number',
            new_name='number',
        ),
    ]
